### ISSUE TITLE
problem about module

### ISSUE THREAD

**Issue by ytyai** [yohatad/Grasp-detection#1]
Is there a missing module? I really can't solve it.
Traceback (most recent call last):
  File "/home/yty/Grasp-detection-master/test.py", line 29, in <module>
    net = torch.load(model_network)
  File "/home/yty/anaconda3/envs/vpg/lib/python3.6/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/yty/anaconda3/envs/vpg/lib/python3.6/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/yty/anaconda3/envs/vpg/lib/python3.6/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'inference.models.grconvnet3'

**Comment by yohatad** [comment]
Fixed
